### ISSUE TITLE
Update Broke Upcoming Assignment and Notice Tabs on Homepage

### ISSUE THREAD

**Issue by haam-man** [BetterSEQTA/BetterSEQTA-Plus#150] opened 2024-08-28 00:08 UTC
Since the 3.3.0 update the upcoming assessments and notice tabs don't display anything for me, the same happens for a few of my friends as well. I've tried deleting the extension and reinstalling and deleting my cache data but it still doesnt work.

![Screenshot 2024-08-28 100613](https://github.com/user-attachments/assets/00278414-042f-4c93-8f27-8f5fb64e7eaf)

**Comment by SethBurkart123** [comment] 2024-08-28 01:04
that's a bit weird! Are you able to `right click` -> `inspect element` and go to the console tab, are there any errors there? They will be red. A screen shot will do fine.

**Comment by haam-man** [comment] 2024-08-28 02:18
Sorry for the late reply.
[cid:0e6fa5b9-9285-44a7-b0b5-c1bfedeb76d4]
________________________________

**Comment by TYP3D** [comment] 2024-08-28 04:48
I can confirm this issue is happening for me too.

**Comment by SethBurkart123** [comment] 2024-08-28 05:06
I believe it should be fixed, i've submitted it to the chrome web store. so hopefully soon it will update to v3.3.1

If the issue is still there then you can reopen the issue!

**Closed by SethBurkart123** 2024-08-28 05:06 UTC

**Comment by ar-cyber** [comment] 2024-08-29 00:05
yeah this is fixed now
