### ISSUE TITLE
Light theme and dark theme hover texts are reversed

### ISSUE THREAD

**Issue by silvncr** [BetterSEQTA/BetterSEQTA-Plus#143] opened 2024-07-29 21:10 UTC
Sorry that the images below are different sizes.

---

When hovering over this icon on the top-right of the screen:

![image](https://github.com/user-attachments/assets/45a1e9c7-166f-4fb7-ac24-926c4b19fb9b)

It seems to display the theme that is already selected, which contradicts the "Switch to..." text.

I think it makes sense to swap the words "light" and "dark", unless I'm missing something.

![image](https://github.com/user-attachments/assets/2c156771-b3c6-4694-9931-534af12bbbb5)

![image](https://github.com/user-attachments/assets/0b5fd9b8-6678-428e-89f5-2b60f92e3ab5)

## Edit

When I reloaded the page in light mode, it displayed a different icon:

![image](https://github.com/user-attachments/assets/8622ae7e-35e2-4c9a-adde-e91a66479f99)

This makes sense and should be kept, but it should change automatically after clicking and not after the page is reloaded.

## Edit 2

The text is actually correct if it hasn't been clicked yet:

![image](https://github.com/user-attachments/assets/722c8fa8-c5ea-4802-8871-d5b17c80a527)

When the button is clicked once, the text does NOT change (which makes it wrong):

![image](https://github.com/user-attachments/assets/fd5e0685-5e50-49ef-a80e-e349ea331361)

When clicked again (and hereafter), the text DOES change:

![image](https://github.com/user-attachments/assets/297bc598-0e23-4c47-9d42-bf041b82f96b)

**Comment by SethBurkart123** [comment] 2024-07-30 06:18
Thanks so much! Fixed as of fed1981

For reference this was caused by a desync between the settings state and the label being updated causing it to use the previous state rather than current.

**Closed by SethBurkart123** 2024-07-30 06:18 UTC
